"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.withErrorHandling = exports.ResourceConflictError = exports.MissingResourceError = exports.InvalidParametersError = exports.InvalidCredentialsError = exports.HTTPError = exports.ExpiredTokenError = exports.AccessForbiddenError = void 0;
var AccessForbiddenError_1 = require("./AccessForbiddenError");
Object.defineProperty(exports, "AccessForbiddenError", { enumerable: true, get: function () { return AccessForbiddenError_1.default; } });
var ExpiredTokenError_1 = require("./ExpiredTokenError");
Object.defineProperty(exports, "ExpiredTokenError", { enumerable: true, get: function () { return ExpiredTokenError_1.default; } });
var HTTPError_1 = require("./HTTPError");
Object.defineProperty(exports, "HTTPError", { enumerable: true, get: function () { return HTTPError_1.default; } });
var InvalidCredentialsError_1 = require("./InvalidCredentialsError");
Object.defineProperty(exports, "InvalidCredentialsError", { enumerable: true, get: function () { return InvalidCredentialsError_1.default; } });
var InvalidParametersError_1 = require("./InvalidParametersError");
Object.defineProperty(exports, "InvalidParametersError", { enumerable: true, get: function () { return InvalidParametersError_1.default; } });
var MissingResourceError_1 = require("./MissingResourceError");
Object.defineProperty(exports, "MissingResourceError", { enumerable: true, get: function () { return MissingResourceError_1.default; } });
var ResourceConflictError_1 = require("./ResourceConflictError");
Object.defineProperty(exports, "ResourceConflictError", { enumerable: true, get: function () { return ResourceConflictError_1.default; } });
var withErrorHandling_1 = require("./withErrorHandling");
Object.defineProperty(exports, "withErrorHandling", { enumerable: true, get: function () { return withErrorHandling_1.default; } });
